set -g status-interval 1
set -g status-right '#(pomo status --short) | %H:%M'

bind-key p run-shell -b 'pomo start 40 >/dev/null 2>&1'
bind-key T command-prompt -p 'Pomodoro minutes:' -I '40' "run-shell -b 'pomo start %1 >/dev/null 2>&1'"
bind-key P run-shell -b 'pomo toggle >/dev/null 2>&1'
bind-key X run-shell -b 'pomo stop >/dev/null 2>&1'
